/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.baseballsimulator;

import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Jinnerfield
 */
public class TeamPicker extends javax.swing.JFrame implements ActionListener {
    
    JTextField[] positions = new JTextField[8];
    JButton[] dropButtons = new JButton[8];
    JButton[] infoButtons = new JButton[8];
    
    public TeamPicker() {
       initComponents();
       positions[0] = catcherText;
       positions[1] = firstBaseText;
       positions[2] = secondBaseText;
       positions[3] = shortStopText;
       positions[4] = thirdBaseText;
       positions[5] = leftFieldText;
       positions[6] = centerFieldText;
       positions[7] = rightFieldText;
       
       dropButtons[0] = catcherDropBtn;
       dropButtons[1] = firstBaseDropBtn;
       dropButtons[2] = secondBaseDropBtn;
       dropButtons[3] = shortStopDropBtn;
       
       dropButtons[4] = thirdBaseDropBtn;
       dropButtons[5] = leftFieldDropBtn;
       dropButtons[6] = centerFieldDropBtn;
       dropButtons[7] = rightFieldDropBtn;
       
       infoButtons[0] = catcherInfo;
       infoButtons[1] = firstBaseInfo;
       infoButtons[2] = secondBaseInfo;
       infoButtons[3] = shortStopInfo;
       infoButtons[4] = thirdBaseInfo;
       infoButtons[5] = leftFieldInfo;
       infoButtons[6] = centerFieldInfo;
       infoButtons[7] = rightFieldInfo;
       
       setupButtonListeners();
       setDropButtons();
    }
    
    private void setDropButtons(){
        for(int i = 0; i<8; i++){
            dropButtons[i].setEnabled(false);
        }
    }
    
    private void dropPlayer(int i){
        positions[i].setText("Empty");
        setDropButtons();
    }
    
    private void positionHandler(String name){   
        for(int i = 0; i<8; i++){
//            System.out.println(positions[0].getText());
            if (positions[i].getText().equals("Empty")){
                positions[i].setText(name);
//                System.out.println(positions[0].getText());
                return;
            }else{
                System.out.println("okay");
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        playerSearch = new javax.swing.JTextPane();
        addBtn = new javax.swing.JButton();
        dropBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        playButton = new javax.swing.JButton();
        catcherText = new javax.swing.JTextField();
        firstBaseText = new javax.swing.JTextField();
        secondBaseText = new javax.swing.JTextField();
        shortStopText = new javax.swing.JTextField();
        thirdBaseText = new javax.swing.JTextField();
        leftFieldText = new javax.swing.JTextField();
        centerFieldText = new javax.swing.JTextField();
        rightFieldText = new javax.swing.JTextField();
        catcherDropBtn = new javax.swing.JButton();
        firstBaseDropBtn = new javax.swing.JButton();
        secondBaseDropBtn = new javax.swing.JButton();
        shortStopDropBtn = new javax.swing.JButton();
        thirdBaseDropBtn = new javax.swing.JButton();
        leftFieldDropBtn = new javax.swing.JButton();
        centerFieldDropBtn = new javax.swing.JButton();
        rightFieldDropBtn = new javax.swing.JButton();
        catcherInfo = new javax.swing.JButton();
        firstBaseInfo = new javax.swing.JButton();
        rightFieldInfo = new javax.swing.JButton();
        centerFieldInfo = new javax.swing.JButton();
        leftFieldInfo = new javax.swing.JButton();
        thirdBaseInfo = new javax.swing.JButton();
        shortStopInfo = new javax.swing.JButton();
        secondBaseInfo = new javax.swing.JButton();

        jButton4.setText("jButton4");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 0));

        playerSearch.setText("Player Last Name");
        jScrollPane1.setViewportView(playerSearch);

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        dropBtn.setText("Drop");
        dropBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel1.setText("Lineup");

        jLabel2.setText("C");

        jLabel3.setText("1B");

        jLabel4.setText("2B");

        jLabel5.setText("SS");

        jLabel6.setText("3B");

        jLabel7.setText("LF");

        jLabel8.setText("CF");

        jLabel9.setText("RF");

        playButton.setText("Simulate");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        catcherText.setText("Empty");
        catcherText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catcherTextActionPerformed(evt);
            }
        });

        firstBaseText.setText("Empty");
        firstBaseText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstBaseTextActionPerformed(evt);
            }
        });

        secondBaseText.setText("Empty");
        secondBaseText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondBaseTextActionPerformed(evt);
            }
        });

        shortStopText.setText("Empty");
        shortStopText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shortStopTextActionPerformed(evt);
            }
        });

        thirdBaseText.setText("Empty");
        thirdBaseText.setToolTipText("");
        thirdBaseText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirdBaseTextActionPerformed(evt);
            }
        });

        leftFieldText.setText("Empty");
        leftFieldText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftFieldTextActionPerformed(evt);
            }
        });

        centerFieldText.setText("Empty");
        centerFieldText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                centerFieldTextActionPerformed(evt);
            }
        });

        rightFieldText.setText("Empty");
        rightFieldText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightFieldTextActionPerformed(evt);
            }
        });

        catcherDropBtn.setBackground(new java.awt.Color(255, 0, 0));
        catcherDropBtn.setForeground(new java.awt.Color(255, 0, 0));

        firstBaseDropBtn.setBackground(new java.awt.Color(255, 0, 0));

        secondBaseDropBtn.setBackground(new java.awt.Color(255, 0, 0));

        shortStopDropBtn.setBackground(new java.awt.Color(255, 0, 0));

        thirdBaseDropBtn.setBackground(new java.awt.Color(255, 0, 0));

        leftFieldDropBtn.setBackground(new java.awt.Color(255, 0, 0));

        centerFieldDropBtn.setBackground(new java.awt.Color(255, 0, 0));

        rightFieldDropBtn.setBackground(new java.awt.Color(255, 0, 0));
        rightFieldDropBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightFieldDropBtnActionPerformed(evt);
            }
        });

        catcherInfo.setText("Info");

        firstBaseInfo.setText("Info");

        rightFieldInfo.setText("Info");

        centerFieldInfo.setText("Info");

        leftFieldInfo.setText("Info");

        thirdBaseInfo.setText("Info");

        shortStopInfo.setText("Info");

        secondBaseInfo.setText("Info");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(rightFieldText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rightFieldDropBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(centerFieldText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(centerFieldDropBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(leftFieldText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(leftFieldDropBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rightFieldInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(centerFieldInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(leftFieldInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(playButton)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(thirdBaseText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(thirdBaseDropBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(shortStopText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(shortStopDropBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(secondBaseText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(secondBaseDropBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(catcherText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(catcherDropBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(firstBaseText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(firstBaseDropBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(shortStopInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(thirdBaseInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(102, 323, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(secondBaseInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, Short.MAX_VALUE)
                                    .addComponent(firstBaseInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(catcherInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addBtn)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dropBtn))
                                .addGap(125, 125, 125))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 11, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(catcherDropBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(catcherText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(catcherInfo, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstBaseDropBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(firstBaseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(secondBaseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(secondBaseInfo))
                                    .addComponent(secondBaseDropBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addBtn)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dropBtn)
                                    .addComponent(firstBaseInfo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(shortStopText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shortStopDropBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(shortStopInfo)
                        .addGap(10, 10, 10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(thirdBaseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thirdBaseDropBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(thirdBaseInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(leftFieldText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leftFieldDropBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leftFieldInfo))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(centerFieldText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(centerFieldDropBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(rightFieldText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(playButton)
                                .addComponent(rightFieldInfo))
                            .addComponent(rightFieldDropBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(centerFieldInfo))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        String var = playerSearch.getText();
        String fullName = PlayerGetter.PlayerGetter(var);
        positionHandler(fullName);
    }//GEN-LAST:event_addBtnActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playButtonActionPerformed

    private void catcherTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catcherTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catcherTextActionPerformed

    private void firstBaseTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstBaseTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstBaseTextActionPerformed

    private void secondBaseTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondBaseTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondBaseTextActionPerformed

    private void shortStopTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shortStopTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shortStopTextActionPerformed

    private void thirdBaseTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirdBaseTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thirdBaseTextActionPerformed

    private void leftFieldTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftFieldTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leftFieldTextActionPerformed

    private void centerFieldTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centerFieldTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_centerFieldTextActionPerformed

    private void rightFieldTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightFieldTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rightFieldTextActionPerformed

    private void dropBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropBtnActionPerformed
        // TODO add your handling code here:
        for (int i=0; i<8; i++){
            dropButtons[i].setEnabled(true);
        }
    }//GEN-LAST:event_dropBtnActionPerformed

    private void rightFieldDropBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightFieldDropBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rightFieldDropBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeamPicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeamPicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeamPicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeamPicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeamPicker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton catcherDropBtn;
    private javax.swing.JButton catcherInfo;
    private javax.swing.JTextField catcherText;
    private javax.swing.JButton centerFieldDropBtn;
    private javax.swing.JButton centerFieldInfo;
    private javax.swing.JTextField centerFieldText;
    private javax.swing.JButton dropBtn;
    private javax.swing.JButton firstBaseDropBtn;
    private javax.swing.JButton firstBaseInfo;
    private javax.swing.JTextField firstBaseText;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton leftFieldDropBtn;
    private javax.swing.JButton leftFieldInfo;
    private javax.swing.JTextField leftFieldText;
    private javax.swing.JButton playButton;
    private javax.swing.JTextPane playerSearch;
    private javax.swing.JButton rightFieldDropBtn;
    private javax.swing.JButton rightFieldInfo;
    private javax.swing.JTextField rightFieldText;
    private javax.swing.JButton secondBaseDropBtn;
    private javax.swing.JButton secondBaseInfo;
    private javax.swing.JTextField secondBaseText;
    private javax.swing.JButton shortStopDropBtn;
    private javax.swing.JButton shortStopInfo;
    private javax.swing.JTextField shortStopText;
    private javax.swing.JButton thirdBaseDropBtn;
    private javax.swing.JButton thirdBaseInfo;
    private javax.swing.JTextField thirdBaseText;
    // End of variables declaration//GEN-END:variables

    public void setupButtonListeners(){
        ActionListener dropButtonListener = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                for (int i=0; i<8; i++){
                        if (e.getSource() == dropButtons[i]){
                            dropPlayer(i);     
                        }
                }
            } 
        };
        ActionListener infoButtonListener = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                try{
                    for (int i=0; i<8; i++){
                        if (e.getSource() == infoButtons[i]){
                            String playerInfoRequested = positions[i].getText().toLowerCase();
                            String url = "https://www.foxsports.com/mlb/" + playerInfoRequested;
                            System.out.println(url);
                            Desktop.getDesktop().browse(new URL(url).toURI());
                        }
                }
                }catch(Exception ae){
                }
            } 
        };
        catcherDropBtn.addActionListener(dropButtonListener);
        firstBaseDropBtn.addActionListener(dropButtonListener);
        secondBaseDropBtn.addActionListener(dropButtonListener);
        shortStopDropBtn.addActionListener(dropButtonListener);
        thirdBaseDropBtn.addActionListener(dropButtonListener);
        leftFieldDropBtn.addActionListener(dropButtonListener);
        centerFieldDropBtn.addActionListener(dropButtonListener);
        rightFieldDropBtn.addActionListener(dropButtonListener);
        
        catcherInfo.addActionListener(infoButtonListener);
        firstBaseInfo.addActionListener(infoButtonListener);
        secondBaseInfo.addActionListener(infoButtonListener);
        shortStopInfo.addActionListener(infoButtonListener);
        thirdBaseInfo.addActionListener(infoButtonListener);
        leftFieldInfo.addActionListener(infoButtonListener);
        centerFieldInfo.addActionListener(infoButtonListener);
        rightFieldInfo.addActionListener(infoButtonListener);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
