/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.baseballsimulator;

import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.util.Arrays;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Jinnerfield
 */
public class TeamPicker extends javax.swing.JFrame implements ActionListener {
    
    JTextField[] positions = new JTextField[9];
    JButton[] dropButtons = new JButton[9];
    JButton[] infoButtons = new JButton[9];
    boolean drop = false;
    boolean add = false;
    boolean sameName = false;
    private String jsonReader;
    private HashMap<String, Float> playerStats = new HashMap<String, Float>();


//    ImageIcon imageTrophy = new ImageIcon("Tropy_Gold.png");
    
    public TeamPicker() {
       initComponents();
       AutoCompleteDecorator.decorate(playerSearchBox);
       positions[0] = catcherText;
       positions[1] = firstBaseText;
       positions[2] = secondBaseText;
       positions[3] = shortStopText;
       positions[4] = thirdBaseText;
       positions[5] = leftFieldText;
       positions[6] = centerFieldText;
       positions[7] = rightFieldText;
       positions[8] = dhText;
       
       dropButtons[0] = catcherDropBtn;
       dropButtons[1] = firstBaseDropBtn;
       dropButtons[2] = secondBaseDropBtn;
       dropButtons[3] = shortStopDropBtn;
       dropButtons[4] = thirdBaseDropBtn;
       dropButtons[5] = leftFieldDropBtn;
       dropButtons[6] = centerFieldDropBtn;
       dropButtons[7] = rightFieldDropBtn;
       dropButtons[8]= dhDropBtn;
       
       infoButtons[0] = catcherInfo;
       infoButtons[1] = firstBaseInfo;
       infoButtons[2] = secondBaseInfo;
       infoButtons[3] = shortStopInfo;
       infoButtons[4] = thirdBaseInfo;
       infoButtons[5] = leftFieldInfo;
       infoButtons[6] = centerFieldInfo;
       infoButtons[7] = rightFieldInfo;
       infoButtons[8] = dhInfo;
       
       setupButtonListeners();
       setDropButtons();
        try {
            // Example JSON array string
            APIHander.playerGetter();
        } catch (IOException ex) {
            Logger.getLogger(TeamPicker.class.getName()).log(Level.SEVERE, null, ex);
        }
         for (int i=0; i<9; i++){
             positions[i].setEditable(false);
         }
    }
    
    private void setDropButtons(){
        for(int i = 0; i<9; i++){
            dropButtons[i].setEnabled(false);
        }
    }
    
    
    private void dropPlayer(int i){
        positions[i].setText("Empty");
        drop = false;
        setDropButtons();     
    }
    
    private void addPlayer(int i){
        //Checks if the name of the player the user is trying to input is already playing another position
        sameName = false;
        for (int j=0; j<9; j++){
            String[] positionNames = playerSearchBox.getSelectedItem().toString().split(" ");
            String positionPlayerName = positionNames[0] + "_" + positionNames[1];
            if (positions[j].getText().equals(positionPlayerName)){
                sameName = true;
            }
        }
        //If the player is not already in the team add the player to the desired position
        if (!sameName){
            String[] formatName = playerSearchBox.getSelectedItem().toString().split(" ");
            String s = formatName[0] + "_" + formatName[1];
            positions[i].setText(s);
        }
        add = false;
        setDropButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        playerSearch = new javax.swing.JTextPane();
        addBtn = new javax.swing.JButton();
        dropBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        catcherText = new javax.swing.JTextField();
        firstBaseText = new javax.swing.JTextField();
        secondBaseText = new javax.swing.JTextField();
        shortStopText = new javax.swing.JTextField();
        thirdBaseText = new javax.swing.JTextField();
        leftFieldText = new javax.swing.JTextField();
        centerFieldText = new javax.swing.JTextField();
        rightFieldText = new javax.swing.JTextField();
        catcherDropBtn = new javax.swing.JButton();
        firstBaseDropBtn = new javax.swing.JButton();
        secondBaseDropBtn = new javax.swing.JButton();
        shortStopDropBtn = new javax.swing.JButton();
        thirdBaseDropBtn = new javax.swing.JButton();
        leftFieldDropBtn = new javax.swing.JButton();
        centerFieldDropBtn = new javax.swing.JButton();
        rightFieldDropBtn = new javax.swing.JButton();
        catcherInfo = new javax.swing.JButton();
        firstBaseInfo = new javax.swing.JButton();
        rightFieldInfo = new javax.swing.JButton();
        centerFieldInfo = new javax.swing.JButton();
        leftFieldInfo = new javax.swing.JButton();
        thirdBaseInfo = new javax.swing.JButton();
        shortStopInfo = new javax.swing.JButton();
        secondBaseInfo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        dhDropBtn = new javax.swing.JButton();
        dhInfo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        dhText = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        simulateButton = new javax.swing.JButton();
        playerSearchBox = new javax.swing.JComboBox<>();
        teamNameComboBox = new javax.swing.JComboBox<>();

        jButton4.setText("jButton4");

        jButton3.setText("jButton3");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        playerSearch.setText("Player Last Name");
        jScrollPane1.setViewportView(playerSearch);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 0));
        setFocusable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 56, -1, -1));

        dropBtn.setText("Drop");
        dropBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropBtnActionPerformed(evt);
            }
        });
        getContentPane().add(dropBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 97, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 51, 204));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("C");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 50, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("1B");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 81, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("2B");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 113, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("SS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 148, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("3B");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 183, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("LF");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 220, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("CF");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 255, -1, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("RF");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 290, -1, -1));

        catcherText.setBackground(new java.awt.Color(255, 255, 255));
        catcherText.setForeground(new java.awt.Color(0, 0, 0));
        catcherText.setText("Empty");
        catcherText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catcherTextActionPerformed(evt);
            }
        });
        getContentPane().add(catcherText, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 47, 80, -1));

        firstBaseText.setBackground(new java.awt.Color(255, 255, 255));
        firstBaseText.setForeground(new java.awt.Color(255, 0, 51));
        firstBaseText.setText("Empty");
        firstBaseText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstBaseTextActionPerformed(evt);
            }
        });
        getContentPane().add(firstBaseText, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 78, 80, -1));

        secondBaseText.setBackground(new java.awt.Color(255, 255, 255));
        secondBaseText.setForeground(new java.awt.Color(0, 0, 0));
        secondBaseText.setText("Empty");
        secondBaseText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondBaseTextActionPerformed(evt);
            }
        });
        getContentPane().add(secondBaseText, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 110, 80, -1));

        shortStopText.setBackground(new java.awt.Color(255, 255, 255));
        shortStopText.setForeground(new java.awt.Color(255, 0, 0));
        shortStopText.setText("Empty");
        shortStopText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shortStopTextActionPerformed(evt);
            }
        });
        getContentPane().add(shortStopText, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 145, 80, -1));

        thirdBaseText.setBackground(new java.awt.Color(255, 255, 255));
        thirdBaseText.setForeground(new java.awt.Color(0, 0, 0));
        thirdBaseText.setText("Empty");
        thirdBaseText.setToolTipText("");
        thirdBaseText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirdBaseTextActionPerformed(evt);
            }
        });
        getContentPane().add(thirdBaseText, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 180, 80, -1));

        leftFieldText.setBackground(new java.awt.Color(255, 255, 255));
        leftFieldText.setForeground(new java.awt.Color(255, 0, 0));
        leftFieldText.setText("Empty");
        leftFieldText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftFieldTextActionPerformed(evt);
            }
        });
        getContentPane().add(leftFieldText, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 217, 80, -1));

        centerFieldText.setBackground(new java.awt.Color(255, 255, 255));
        centerFieldText.setForeground(new java.awt.Color(0, 0, 0));
        centerFieldText.setText("Empty");
        centerFieldText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                centerFieldTextActionPerformed(evt);
            }
        });
        getContentPane().add(centerFieldText, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 252, 80, -1));

        rightFieldText.setBackground(new java.awt.Color(255, 255, 255));
        rightFieldText.setForeground(new java.awt.Color(255, 0, 0));
        rightFieldText.setText("Empty");
        rightFieldText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightFieldTextActionPerformed(evt);
            }
        });
        getContentPane().add(rightFieldText, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 287, 80, -1));

        catcherDropBtn.setBackground(new java.awt.Color(255, 0, 0));
        catcherDropBtn.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(catcherDropBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 47, 18, 22));

        firstBaseDropBtn.setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().add(firstBaseDropBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 78, 18, 22));

        secondBaseDropBtn.setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().add(secondBaseDropBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 111, 18, 22));

        shortStopDropBtn.setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().add(shortStopDropBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 145, 18, 22));

        thirdBaseDropBtn.setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().add(thirdBaseDropBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 180, 18, 22));

        leftFieldDropBtn.setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().add(leftFieldDropBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 217, 18, 22));

        centerFieldDropBtn.setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().add(centerFieldDropBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 252, 18, 23));

        rightFieldDropBtn.setBackground(new java.awt.Color(255, 0, 0));
        rightFieldDropBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightFieldDropBtnActionPerformed(evt);
            }
        });
        getContentPane().add(rightFieldDropBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 287, 18, 23));

        catcherInfo.setText("Info");
        getContentPane().add(catcherInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 46, 54, -1));

        firstBaseInfo.setText("Info");
        getContentPane().add(firstBaseInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 78, 54, -1));

        rightFieldInfo.setText("Info");
        getContentPane().add(rightFieldInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 287, 54, -1));

        centerFieldInfo.setText("Info");
        getContentPane().add(centerFieldInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 252, 54, -1));

        leftFieldInfo.setText("Info");
        getContentPane().add(leftFieldInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 217, 54, -1));

        thirdBaseInfo.setText("Info");
        getContentPane().add(thirdBaseInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 182, 54, -1));

        shortStopInfo.setText("Info");
        getContentPane().add(shortStopInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 147, 54, -1));

        secondBaseInfo.setText("Info");
        getContentPane().add(secondBaseInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 110, 54, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("DH");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 326, -1, -1));

        dhDropBtn.setBackground(new java.awt.Color(255, 0, 0));
        dhDropBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dhDropBtnActionPerformed(evt);
            }
        });
        getContentPane().add(dhDropBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 322, 18, 23));

        dhInfo.setText("Info");
        getContentPane().add(dhInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 322, 54, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        dhText.setBackground(new java.awt.Color(255, 255, 255));
        dhText.setForeground(new java.awt.Color(0, 0, 0));
        dhText.setText("Empty");
        dhText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dhTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(dhText, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(282, Short.MAX_VALUE)
                .addComponent(dhText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 210, 310));

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setFocusable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Lineup");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        simulateButton.setText("Simulate");
        simulateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulateButtonActionPerformed(evt);
            }
        });

        playerSearchBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Player", "Miguel Cabrera", "Yadier Molina", "Robinson Cano", "Kurt Suzuki", "Nelson Cruz", "David Peralta", "Manny Pina", "Alcides Escobar", "Evan Longoria", "Charlie Blackmon", "Martin Maldonado", "Robinson Chirinos", "Lorenzo Cain", "Donovan Solano", "Andrew McCutchen", "Justin Upton", "Justin Turner", "Joey Votto", "Elvis Andrus", "Carlos Santana", "Brandon Belt", "Jed Lowrie", "Michael Brantley", "Jason Castro", "Yuli Gurriel", "Miguel Rojas", "Eduardo Escobar", "Ehire Adrianza", "Juan Lagares", "Abraham Almonte", "Tommy Pham", "J.D. Martinez", "Paul Goldschmidt", "Marwin Gonzalez", "Sandy Leon", "Jose Altuve", "Cesar Hernandez", "Jean Segura", "Starling Marte", "Charlie Culberson", "Travis d'Arnaud", "Josh Donaldson", "Freddie Freeman", "Yasmani Grandal", "Jason Heyward", "DJ LeMahieu", "Mike Moustakas", "Anthony Rizzo", "Austin Romine", "Steven Souza", "Giancarlo Stanton", "Stephen Vogt", "Salvador Perez", "Wilmer Flores", "Avisail Garcia", "Christian Bethancourt", "Marcell Ozuna", "Jonathan Villar", "Rafael Ortega", "Jesus Aguilar", "Tim Beckham", "Jon Berti", "Brandon Crawford", "C.J. Cron", "Alex Dickerson", "Yan Gomes", "Robbie Grossman", "Josh Harrison", "Aaron Hicks", "Kyle Higashioka", "Eric Hosmer", "James McCann", "Brad Miller", "Austin Nola", "Anthony Rendon", "Marcus Semien", "Travis Shaw", "George Springer", "Dee Strange-Gordon", "Christian Vazquez", "Kolten Wong", "Didi Gregorius", "Leury Garcia", "Ildemaro Vargas", "Randal Grichuk", "Jake Marisnick", "Max Stassi", "Mike Trout", "Odubel Herrera", "Albert Almora", "Christian Lopes", "Bryce Harper", "Roberto Perez", "Jose Abreu", "Elias Diaz", "Omar Narvaez", "Willians Astudillo", "Dixon Machado", "Eugenio Suarez", "Erik Gonzalez", "Gio Urshela", "Carlos Sanchez", "Jonathan Schoop", "Nolan Arenado", "Tucker Barnhart", "Matt Davidson", "Kyle Farmer", "Billy Hamilton", "Mitch Haniger", "Enrique Hernandez", "Jake Lamb", "Luke Maile", "Max Muncy", "Wil Myers", "Tyler Naquin", "Chris Owings", "Stephen Piscotty", "AJ Pollock", "Michael Taylor", "Trayce Thompson", "Luke Voit", "Christian Walker", "Mike Zunino", "Matt Carpenter", "Corey Dickerson", "Dustin Garneau", "Darin Ruf", "Mike Yastrzemski", "Willson Contreras", "Jose Iglesias", "Wynton Bernard", "Kris Bryant", "Mark Canha", "Curt Casali", "Nick Castellanos", "Brandon Drury", "Ben Gamel", "Niko Goodrum", "Aaron Judge", "Manny Machado", "Colin Moran", "Mark Payton", "Joc Pederson", "J.T. Realmuto", "Hunter Renfroe", "Eddie Rosario", "Andrelton Simmons", "Christian Yelich", "Whit Merrifield", "Xander Bogaerts", "Hanser Alberto", "Jorge Polanco", "Miguel Sano", "Kole Calhoun", "Adam Duvall", "Phil Gosselin", "Kevin Kiermaier", "Andrew Knapp", "Chad Wallach", "Jorge Alfaro", "Jurickson Profar", "Javier Baez", "Jake Cave", "Cam Gallagher", "Austin Hedges", "Francisco Lindor", "Rougned Odor", "Austin Slater", "Trevor Story", "Garrett Stubbs", "Daniel Vogelbach", "Gary Sanchez", "Max Kepler", "Roman Quinn", "Maikel Franco", "Ji-Man Choi", "Jackie Bradley", "Tommy LaStella", "Pedro Severino", "Jeimer Candelario", "Yonathan Daza", "Ramon Urias", "Nick Ahmed", "Brian Anderson", "Austin Barnes", "Josh Bell", "Mookie Betts", "Victor Caratini", "J.D. Davis", "Aramis Garcia", "Vimael Machin", "Michael Perez", "Dillon Thomas", "Bradley Zimmer", "Harold Castro", "Esteban Quiroz", "Orlando Arcia", "Raimel Tapia", "Aristides Aquino", "Teoscar Hernandez", "Yermin Mercedes", "Ketel Marte", "Eric Haase", "Jake Hager", "Brandon Nimmo", "Jace Peterson", "Trea Turner", "Jason Krizan", "Matt Beaty", "Kevin Pillar", "Jacob Stallings", "Jose Ramirez", "Alex Bregman", "Joey Gallo", "Carson Kelly", "Chris Okey", "Corey Seager", "Jesse Winker", "Jose Godoy", "Nomar Mazara", "Tom Murphy", "Travis Jankowski", "Jack Mayfield", "Kevin Plawecki", "Rob Refsnyder", "Matt Reynolds", "Joey Meneses", "Elier Hernandez", "Adalberto Mondesi", "Miguel Andujar", "Jason Vosler", "Franchy Cordero", "Franmil Reyes", "Luis Torrens", "Richie Martin", "Max Schrock", "Dansby Swanson", "Kevin Newman", "Chris Taylor", "Carlos Correa", "Brett Phillips", "Tyrone Taylor", "Byron Buxton", "Lewis Brinson", "Skye Bolt", "Steven Duggar", "Edwin Rios", "Taylor Ward", "Tomas Nido", "Anthony Bemboom", "Patrick Wisdom", "Joey Wendle", "Matt Olson", "Matt Duffy", "Yairo Munoz", "Donovan Walton", "Manuel Margot", "Pablo Reyes", "Johan Camargo", "Victor Reyes", "Jorge Mateo", "Tyler Heineman", "Andrew Velazquez", "David Bote", "Harold Ramirez", "Anthony Santander", "Pete Alonso", "Christian Arroyo", "Cavan Biggio", "Adam Frazier", "Jose Trevino", "Nick Gordon", "Reese McGuire", "Dom Nunez", "Jorge Soler", "Edmundo Sosa", "Guillermo Heredia", "Yadiel Hernandez", "Andy Ibanez", "Jake Cronenworth", "Clint Frazier", "Austin Meadows", "Oscar Mercado", "Chad Pinder", "Jose Azocar", "Tim Anderson", "Cody Bellinger", "Willie Calhoun", "Zack Collins", "J.P. Crawford", "Jonathan Davis", "Jason Delay", "Ben DeLuzio", "Travis Demeritte", "Brandon Dixon", "Hunter Dozier", "Adam Engel", "Jake Fraley", "Mitch Garver", "Luis Guillorme", "Garrett Hampson", "Jonah Heim", "Michael Hermosillo", "Gosuke Katoh", "Charles Leblanc", "Kyle Lewis", "Tim Locastro", "Trey Mancini", "Billy McKinney", "Ryan McMahon", "Sheldon Neuse", "Tyler O'Neill", "Josh Palacios", "Chuckie Robinson", "Dominic Smith", "Rowdy Tellez", "Matt Thaiss", "Cody Thomas", "Josh VanMeter", "Tyler Wade", "Eli White", "Francisco Mejia", "Jose Siri", "Magneuris Sierra", "Luis Barrera", "Amed Rosario", "Willy Adames", "Kelvin Gutierrez", "Sergio Alcantara", "Thairo Estrada", "Austin Wynns", "Andrew Benintendi", "Garrett Cooper", "Mauricio Dubon", "Caleb Hamilton", "Danny Jansen", "Tony Kemp", "Isiah Kiner-Falefa", "Jeff McNeil", "Frank Schwindel", "Yu Chang", "Ozzie Albies", "Victor Robles", "Jose Herrera", "Mike Ford", "Rafael Devers", "Josh Naylor", "Abraham Toro", "Aledmys Diaz", "Luis Urias", "Lewin Diaz", "Luis Arraez", "Jermaine Palacios", "Eloy Jimenez", "Gleyber Torres", "Willi Castro", "Yandy Diaz", "Bryan DeLaCruz", "Meibrys Viloria", "Luis Rengifo", "Rene Pinto", "Carlos Perez", "Riley Adams", "Greg Allen", "Sean Bouchard", "Bobby Bradley", "Matt Chapman", "Michael Chavis", "Joe Dunand", "Drew Ellis", "Stuart Fairchild", "Stone Garrett", "Dalton Guthrie", "Monte Harrison", "Adam Haseley", "Derek Hill", "Sam Hilliard", "Rhys Hoskins", "Alex Jackson", "Connor Joe", "Mark Kolozsvary", "Jordan Luplow", "J.J. Matijevic", "Zach McKinstry", "Cedric Mullins", "Ryan O'Hearn", "Kevin Padlo", "Emmanuel Rivera", "Kyle Schwarber", "Pavin Smith", "Lane Thomas", "Cole Tucker", "Alex Verdugo", "Connor Wong", "Eddy Alvarez", "Paul DeJong", "Ramon Laureano", "Michael Papierski", "Gavin Sheets", "Edward Olivares", "Yoan Moncada", "Shohei Ohtani", "Yoshi Tsutsugo", "Jonathan Arauz", "Yonny Hernandez", "Diego Castillo", "Vidal Brujan", "Dermis Garcia", "Ronald Acuna", "Keibert Ruiz", "Elehuris Montero", "Oscar Gonzalez", "Juan Yepez", "Jesus Sanchez", "Hoy Park", "William Contreras", "Brian Serven", "Daulton Varsho", "Lars Nootbaar", "Brendon Davis", "Tyler Nevin", "Nico Hoerner", "Austin Riley", "Nick Madrigal", "Trevor Larnach", "Ryan Mountcastle", "Ryan McKenna", "Ke'Bryan Hayes", "Kyle Tucker", "Daz Cameron", "Jonathan India", "Joey Bart", "Cal Raleigh", "Nick Fortes", "Trent Grisham", "Matt Vierling", "Alfonso Rivas", "Romy Gonzalez", "Tyler Stephenson", "Luke Williams", "Brendan Rodgers", "Nick Plummer", "Nathaniel Lowe", "Ian Happ", "Mark Mathias", "Ty France", "Brandon Lowe", "Jaylin Davis", "Harrison Bader", "David Fletcher", "Sam Haggerty", "Austin Allen", "Dylan Moore", "Kyle Garlick", "Estevan Florial", "Aaron Whitefield", "Alejo Lopez", "Myles Straw", "Kyle Isbel", "P.J. Higgins", "Alec Bohm", "LaMonte Wade", "Patrick Mazeika", "Seby Zavala", "Danny Mendick", "Seth Brown", "Jake McCarthy", "Kody Clemens", "Jared Walsh", "Ford Proctor", "Nick Maton", "Jeremy Pena", "Gilberto Celestino", "Vladimir Guerrero", "Cristian Pache", "Lucius Fox", "Juan Soto", "Leody Taveras", "Oswaldo Cabrera", "Oneil Cruz", "Sebastian Rivero", "Jazz Chisholm", "Esteury Ruiz", "Andres Gimenez", "Jonathan Aranda", "Nolan Jones", "Alex Kirilloff", "Josh Lowe", "Gavin Lux", "Mickey Moniak", "Jo Adell", "Seth Beer", "Will Benson", "Bo Bichette", "Dylan Carlson", "Taylor Trammell", "Jerar Encarnacion", "Christopher Morel", "Rodolfo Castro", "Bobby Dalbec", "Ryan Aguilar", "Adolis Garcia", "Lourdes Gurriel", "Brent Rooker", "Steele Walker", "Randy Arozarena", "Nick Pratto", "Tres Barrera", "JJ Bleday", "Spencer Steer", "Payton Henry", "Akil Baddoo", "Cal Mitchell", "Andrew Knizner", "Bryan Reynolds", "Conner Capel", "Mark Vientos", "Royce Lewis", "Adley Rutschman", "Josh Rojas", "Ryan Kreidler", "Garrett Mitchell", "MJ Melendez", "Brandon Marsh", "Jeter Downs", "Kyle Stowers", "Sam Huff", "Shea Langeliers", "Luis Campusano", "Sean Murphy", "Nick Senzel", "Tommy Edman", "Nick Solak", "Will Smith", "Jack Suwinski", "Santiago Espinal", "Jose Miranda", "Bubba Thompson", "Nolan Gorman", "Bryce Johnson", "Keston Hiura", "Jake Burger", "Nick Allen", "Cooper Hummel", "Josh Smith", "Austin Hays", "Darick Hall", "Alex Call", "Michael Toglia", "Nicky Lopez", "Luke Raley", "Zack Short", "Miles Mastrobuoni", "Matt Wallner", "Cal Stevenson", "Jose Rojas", "Yordan Alvarez", "Isaac Paredes", "Mike Brosseau", "Taylor Walls", "Luis Gonzalez", "TJ Friedl", "Livan Soto", "Ivan Herrera", "Buddy Kennedy", "Triston Casas", "Heliot Ramos", "Drew Waters", "Luis Garcia", "Tyler Freeman", "Michael Harris", "Michael Siani", "Jarred Kelenic", "Gabriel Arias", "Alejandro Kirk", "Jordan Diaz", "Gabriel Moreno", "Maikel Garcia", "Otto Lopez", "Geraldo Perdomo", "Oswald Peraza", "Tucupita Marcano", "Lenyn Sosa", "Israel Pineda", "Luis Robert", "Ha-Seong Kim", "Seiya Suzuki", "Josh Jung", "Kevin Smith", "Nelson Velazquez", "Ernie Clement", "Alec Burleson", "Jose Barrero" }));
        playerSearchBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerSearchBoxActionPerformed(evt);
            }
        });

        teamNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a Team", "Diamondbacks", "Braves", "Orioles", "Red Sox", "White Sox", "Cubs", "Reds", "Guardians", "Rockies", "Tigers", "Astros", "Royals", "Angels", "Dodgers", "Marlins", "Brewers", "Twins", "Yankees", "Mets", "Athletics", "Phillies", "Pirates", "Padres", "Giants", "Mariners", "Cardinals", "Rays", "Rangers", "Blue Jays", "Nationals" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                        .addComponent(simulateButton)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(playerSearchBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(teamNameComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(playerSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(teamNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(simulateButton)
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 570, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        for (int i=0; i<9; i++){
            dropButtons[i].setEnabled(true);
            dropButtons[i].setBackground(Color.green);
            add = true;
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void simulateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulateButtonActionPerformed
        
        Simulate.getInstance();
        boolean positionsFilled = ExceptionHandler.lineupFilled(positions);
        if (!positionsFilled){
            JOptionPane.showMessageDialog(null, "Not Enough Players In Your Team", "ALERT", JOptionPane.ERROR_MESSAGE);
        }else if(teamNameComboBox.getSelectedItem().equals("Choose a Team")){
            JOptionPane.showMessageDialog(null, "No Team Selected", "ALERT", JOptionPane.ERROR_MESSAGE);
        }else{
            playerStats = APIHander.xwobaGetter();
            playerStats = APIHander.playerSeasonSim(playerStats);
            String[] catcherName = catcherText.getText().split("_");
            String[] firstBaseName = firstBaseText.getText().split("_");
            String[] secondBaseName = secondBaseText.getText().split("_");
            String[] thirdBaseName = thirdBaseText.getText().split("_");
            String[] shortStopName = shortStopText.getText().split("_");
            String[] leftFieldName = leftFieldText.getText().split("_");
            String[] centerFieldName = centerFieldText.getText().split("_");
            String[] rightFieldName = rightFieldText.getText().split("_");
            String[] dhName = dhText.getText().split("_");
            APIHander.yourTeamWobaGetter(catcherName[1], firstBaseName[1], secondBaseName[1], thirdBaseName[1], shortStopName[1], leftFieldName[1], centerFieldName[1], rightFieldName[1], dhName[1], teamNameComboBox.getSelectedItem().toString());
            Simulate pi = new Simulate();
            String mvpFullName = APIHander.returnMVP(playerStats);
            Simulate.setMVP(mvpFullName);
            String mvpStats = APIHander.playerStatsGetter(mvpFullName);
            Simulate.setMVPStats(mvpStats);
            Simulate.lineupPlayerTableInsert(catcherText.getText(), APIHander.playerStatsGetter(catcherText.getText()), firstBaseText.getText(), APIHander.playerStatsGetter(firstBaseText.getText()), secondBaseText.getText(), APIHander.playerStatsGetter(secondBaseText.getText()), thirdBaseText.getText(), APIHander.playerStatsGetter(thirdBaseText.getText()), shortStopText.getText(), APIHander.playerStatsGetter(shortStopText.getText()), leftFieldText.getText(), APIHander.playerStatsGetter(leftFieldText.getText()), centerFieldText.getText(), APIHander.playerStatsGetter(centerFieldText.getText()), rightFieldText.getText(), APIHander.playerStatsGetter(rightFieldText.getText()), dhText.getText(), APIHander.playerStatsGetter(dhText.getText()));
            pi.setVisible(true);
        }
    }//GEN-LAST:event_simulateButtonActionPerformed

    private void catcherTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catcherTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catcherTextActionPerformed

    private void firstBaseTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstBaseTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstBaseTextActionPerformed

    private void secondBaseTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondBaseTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondBaseTextActionPerformed

    private void shortStopTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shortStopTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shortStopTextActionPerformed

    private void thirdBaseTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirdBaseTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thirdBaseTextActionPerformed

    private void leftFieldTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftFieldTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leftFieldTextActionPerformed

    private void centerFieldTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centerFieldTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_centerFieldTextActionPerformed

    private void rightFieldTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightFieldTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rightFieldTextActionPerformed

    private void dropBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropBtnActionPerformed
        // TODO add your handling code here:
        for (int i=0; i<9; i++){
            dropButtons[i].setEnabled(true);
            dropButtons[i].setBackground(Color.red);
            drop = true;
            String[] test = catcherText.getText().split("_");
            System.out.println(test[1]);
        }
    }//GEN-LAST:event_dropBtnActionPerformed

    private void rightFieldDropBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightFieldDropBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rightFieldDropBtnActionPerformed

    private void dhTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dhTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dhTextActionPerformed

    private void dhDropBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dhDropBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dhDropBtnActionPerformed

    private void playerSearchBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerSearchBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerSearchBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeamPicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeamPicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeamPicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeamPicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeamPicker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton catcherDropBtn;
    private javax.swing.JButton catcherInfo;
    private javax.swing.JTextField catcherText;
    private javax.swing.JButton centerFieldDropBtn;
    private javax.swing.JButton centerFieldInfo;
    private javax.swing.JTextField centerFieldText;
    private javax.swing.JButton dhDropBtn;
    private javax.swing.JButton dhInfo;
    private javax.swing.JTextField dhText;
    private javax.swing.JButton dropBtn;
    private javax.swing.JButton firstBaseDropBtn;
    private javax.swing.JButton firstBaseInfo;
    private javax.swing.JTextField firstBaseText;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton leftFieldDropBtn;
    private javax.swing.JButton leftFieldInfo;
    private javax.swing.JTextField leftFieldText;
    private javax.swing.JTextPane playerSearch;
    private javax.swing.JComboBox<String> playerSearchBox;
    private javax.swing.JButton rightFieldDropBtn;
    private javax.swing.JButton rightFieldInfo;
    private javax.swing.JTextField rightFieldText;
    private javax.swing.JButton secondBaseDropBtn;
    private javax.swing.JButton secondBaseInfo;
    private javax.swing.JTextField secondBaseText;
    private javax.swing.JButton shortStopDropBtn;
    private javax.swing.JButton shortStopInfo;
    private javax.swing.JTextField shortStopText;
    private javax.swing.JButton simulateButton;
    private javax.swing.JComboBox<String> teamNameComboBox;
    private javax.swing.JButton thirdBaseDropBtn;
    private javax.swing.JButton thirdBaseInfo;
    private javax.swing.JTextField thirdBaseText;
    // End of variables declaration//GEN-END:variables

    public void setupButtonListeners(){
        ActionListener dropButtonListener = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                for (int i=0; i<9; i++){
                    if (drop == true){
                        if (e.getSource() == dropButtons[i]){
                            dropPlayer(i);     
                        }
                    }
                    if (add == true){ 
                        if (e.getSource() == dropButtons[i]){
                            addPlayer(i);     
                        }
                    }
                }
            } 
        };
        ActionListener infoButtonListener = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                try{
                    for (int i=0; i<9; i++){
                        if (e.getSource() == infoButtons[i]){
                            String playerInfoRequested = positions[i].getText().toLowerCase();
                            String[] tempNameBuilder = playerInfoRequested.split("_");
                            String playerSearchName = tempNameBuilder[0] + "-" + tempNameBuilder[1];
                            String url = "https://www.foxsports.com/mlb/" + playerSearchName;
                            System.out.println(url);
                            Desktop.getDesktop().browse(new URL(url).toURI());
                        }
                }
                }catch(Exception ae){
                }
            } 
        };
        catcherDropBtn.addActionListener(dropButtonListener);
        firstBaseDropBtn.addActionListener(dropButtonListener);
        secondBaseDropBtn.addActionListener(dropButtonListener);
        shortStopDropBtn.addActionListener(dropButtonListener);
        thirdBaseDropBtn.addActionListener(dropButtonListener);
        leftFieldDropBtn.addActionListener(dropButtonListener);
        centerFieldDropBtn.addActionListener(dropButtonListener);
        rightFieldDropBtn.addActionListener(dropButtonListener);
        dhDropBtn.addActionListener(dropButtonListener);
        
        catcherInfo.addActionListener(infoButtonListener);
        firstBaseInfo.addActionListener(infoButtonListener);
        secondBaseInfo.addActionListener(infoButtonListener);
        shortStopInfo.addActionListener(infoButtonListener);
        thirdBaseInfo.addActionListener(infoButtonListener);
        leftFieldInfo.addActionListener(infoButtonListener);
        centerFieldInfo.addActionListener(infoButtonListener);
        rightFieldInfo.addActionListener(infoButtonListener);
        dhInfo.addActionListener(infoButtonListener);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
